import { useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, ExternalLink, FolderOpen, Pencil, Plus, Search, Star, Trash2, X } from 'lucide-react';
import type { MonitoredFolder } from '../types';
import { domainIcon, folderSort, formatDate, normalizeUrl, validateUrl } from '../utils';

const categories = ['Drive', 'YouTube', 'Planilhas', 'Projetos', 'Outro'];
type Props = { folders: MonitoredFolder[]; onChange: (folders: MonitoredFolder[]) => void; onNotify: (message: string) => void };
const blank = { name: '', url: '', category: 'Outro' };

export function FolderSection({ folders, onChange, onNotify }: Props) {
  const [draft, setDraft] = useState(blank); const [editing, setEditing] = useState<string | null>(null); const [query, setQuery] = useState(''); const [category, setCategory] = useState('Todas'); const [sort, setSort] = useState('favorite'); const [error, setError] = useState('');
  const visible = useMemo(() => folderSort(folders.filter(folder => (category === 'Todas' || folder.category === category) && `${folder.name} ${folder.url}`.toLowerCase().includes(query.toLowerCase())), sort), [folders, query, category, sort]);
  const submit = () => { const urlError = validateUrl(draft.url); if (urlError) { setError(urlError); return; } const url = normalizeUrl(draft.url); const existing = editing ? folders.find(folder => folder.id === editing) : undefined; const next = { id: editing || `folder-${Date.now()}`, name: draft.name.trim() || new URL(url).hostname, url, category: draft.category, favorite: existing?.favorite || false, order: existing?.order ?? folders.length, updatedAt: new Date().toISOString() }; onChange(editing ? folders.map(folder => folder.id === editing ? next : folder) : [...folders, next]); onNotify(editing ? 'Link atualizado.' : 'Link adicionado.'); setDraft(blank); setEditing(null); setError(''); };
  const edit = (folder: MonitoredFolder) => { setEditing(folder.id); setDraft({ name: folder.name, url: folder.url, category: folder.category }); setError(''); };
  const remove = (folder: MonitoredFolder) => { if (!window.confirm(`Excluir o link "${folder.name}"?`)) return; onChange(folders.filter(item => item.id !== folder.id)); onNotify('Link excluído. Você pode restaurá-lo pelo backup local.'); };
  const move = (folder: MonitoredFolder, direction: number) => { const index = folders.findIndex(item => item.id === folder.id); const target = index + direction; if (target < 0 || target >= folders.length) return; const copy = [...folders]; [copy[index], copy[target]] = [copy[target], copy[index]]; onChange(copy.map((item, order) => ({ ...item, order }))); };
  return <section className="panel monitored-section" aria-labelledby="folders-title">
    <div className="section-heading"><div><p className="eyebrow">Acesso rápido</p><h2 id="folders-title">Pastas Monitoradas</h2><p>Centralize os espaços usados na operação.</p></div><button className="primary-button" onClick={() => { setEditing(''); setDraft(blank); }}><Plus size={16} /> Adicionar link</button></div>
    <div className="folder-toolbar"><label className="search-field"><Search size={16} /><span className="sr-only">Buscar links</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar por nome ou URL" /></label><select value={category} onChange={event => setCategory(event.target.value)} aria-label="Filtrar por categoria"><option>Todas</option>{categories.map(item => <option key={item}>{item}</option>)}</select><select value={sort} onChange={event => setSort(event.target.value)} aria-label="Ordenar links"><option value="favorite">Favoritos primeiro</option><option value="recent">Atualizados recentemente</option><option value="name">Nome A-Z</option></select></div>
    {(editing !== null) && <div className="editor-panel" role="dialog" aria-label={editing ? 'Editar link' : 'Adicionar link'}><div className="form-grid"><label>Nome<input autoFocus value={draft.name} onChange={event => setDraft({ ...draft, name: event.target.value })} placeholder="Ex.: Drive da equipe" /></label><label>URL<input value={draft.url} onChange={event => { setDraft({ ...draft, url: event.target.value }); setError(''); }} onKeyDown={event => event.key === 'Enter' && submit()} placeholder="https://..." aria-invalid={Boolean(error)} />{error && <span className="field-error" role="alert">{error}</span>}</label><label>Categoria<select value={draft.category} onChange={event => setDraft({ ...draft, category: event.target.value })}>{categories.map(item => <option key={item}>{item}</option>)}</select></label></div><div className="form-actions"><button className="primary-button" onClick={submit}>Salvar</button><button className="secondary-button" onClick={() => { setEditing(null); setError(''); }}><X size={15} /> Cancelar</button></div></div>}
    <div className="folder-grid" aria-live="polite">{visible.length === 0 ? <div className="empty-state"><FolderOpen size={22} /><span>{query || category !== 'Todas' ? 'Nenhum link corresponde aos filtros.' : 'Nenhum link monitorado ainda.'}</span></div> : visible.map(folder => <article className="folder-card" key={folder.id}><button className={'icon-button favorite-button' + (folder.favorite ? ' is-favorite' : '')} aria-label={folder.favorite ? `Remover ${folder.name} dos favoritos` : `Favoritar ${folder.name}`} onClick={() => onChange(folders.map(item => item.id === folder.id ? { ...item, favorite: !item.favorite, updatedAt: new Date().toISOString() } : item))}><Star size={16} fill={folder.favorite ? 'currentColor' : 'none'} /></button><img className="folder-favicon" src={domainIcon(folder.url)} alt="" onError={event => { event.currentTarget.style.display = 'none'; }} /><div className="folder-info"><strong>{folder.name}</strong><span>{folder.category} · atualizado em {formatDate(folder.updatedAt)}</span><small>{folder.url}</small></div><a className="icon-button" href={folder.url} target="_blank" rel="noreferrer" aria-label={`Abrir ${folder.name}`}><ExternalLink size={16} /></a><div className="card-actions"><button className="icon-button" aria-label={`Editar ${folder.name}`} onClick={() => edit(folder)}><Pencil size={15} /></button><button className="icon-button" aria-label={`Mover ${folder.name} para cima`} onClick={() => move(folder, -1)}><ArrowUp size={15} /></button><button className="icon-button" aria-label={`Mover ${folder.name} para baixo`} onClick={() => move(folder, 1)}><ArrowDown size={15} /></button><button className="icon-button danger" aria-label={`Excluir ${folder.name}`} onClick={() => remove(folder)}><Trash2 size={15} /></button></div></article>)}</div>
  </section>;
}
