import { useMemo, useState } from 'react';
import { Check, Clock3, GripVertical, History, Plus, Search, Trash2, Undo2, X } from 'lucide-react';
import type { Priority, Stage, StageId, Task } from '../types';
import { formatDate, taskMatches } from '../utils';

type Props = { stages: Stage[]; onChange: (stages: Stage[]) => void; onNotify: (message: string) => void };
const priorityNames: Record<Priority, string> = { baixa: 'Baixa', media: 'Média', alta: 'Alta' };
const emptyDraft = { title: '', assignee: '', dueDate: '', priority: 'media' as Priority, labels: '' };

export function TaskBoard({ stages, onChange, onNotify }: Props) {
  const [query, setQuery] = useState('');
  const [stageFilter, setStageFilter] = useState('Todos');
  const [priority, setPriority] = useState('Todas');
  const [editing, setEditing] = useState<{ task: Task; stageId: StageId } | null>(null);
  const [draft, setDraft] = useState(emptyDraft);
  const [adding, setAdding] = useState<StageId | null>(null);
  const [undo, setUndo] = useState<{ stages: Stage[]; title: string } | null>(null);
  const [draggedTaskId, setDraggedTaskId] = useState<string | null>(null);
  const [dropTargetId, setDropTargetId] = useState<StageId | null>(null);

  const filtered = useMemo(() => stages.filter(stage => stageFilter === 'Todos' || stage.name === stageFilter).map(stage => ({ ...stage, tasks: stage.tasks.filter(task => taskMatches(task, query) && (priority === 'Todas' || task.priority === priority)) })), [stages, stageFilter, query, priority]);
  const openEdit = (task: Task, stageId: StageId) => { setEditing({ task, stageId }); setDraft({ title: task.title, assignee: task.assignee || '', dueDate: task.dueDate || '', priority: task.priority, labels: task.labels.join(', ') }); };
  const save = () => { if (!editing || !draft.title.trim()) return; const at = new Date().toISOString(); const updated = { ...editing.task, title: draft.title.trim(), assignee: draft.assignee.trim(), dueDate: draft.dueDate, priority: draft.priority, labels: draft.labels.split(',').map(label => label.trim()).filter(Boolean), history: [...editing.task.history, { id: `history-${Date.now()}`, action: 'Edição', detail: `Alteração em ${at}`, at }] }; onChange(stages.map(stage => stage.id === editing.stageId ? { ...stage, tasks: stage.tasks.map(task => task.id === editing.task.id ? updated : task) } : stage)); setEditing(null); onNotify('Tarefa salva.'); };
  const add = (stageId: StageId) => { if (!draft.title.trim()) return; const task: Task = { id: `task-${Date.now()}`, title: draft.title.trim(), assignee: draft.assignee.trim(), dueDate: draft.dueDate, priority: draft.priority, labels: draft.labels.split(',').map(label => label.trim()).filter(Boolean), history: [{ id: `history-${Date.now()}`, action: 'Criação', detail: 'Tarefa criada', at: new Date().toISOString() }] }; onChange(stages.map(stage => stage.id === stageId ? { ...stage, tasks: [...stage.tasks, task] } : stage)); setAdding(null); setDraft(emptyDraft); onNotify('Tarefa adicionada.'); };
  const remove = (stageId: StageId, task: Task) => { if (!window.confirm(`Excluir a tarefa "${task.title}"?`)) return; setUndo({ stages, title: task.title }); onChange(stages.map(stage => stage.id === stageId ? { ...stage, tasks: stage.tasks.filter(item => item.id !== task.id) } : stage)); onNotify('Tarefa excluída.'); };
  const restore = () => { if (!undo) return; onChange(undo.stages); setUndo(null); onNotify('Tarefa restaurada.'); };
  const handleDragStart = (event: React.DragEvent, taskId: string) => { event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', taskId); setDraggedTaskId(taskId); };
  const handleDrop = (event: React.DragEvent, targetStageId: StageId, beforeTaskId?: string) => { event.preventDefault(); event.stopPropagation(); const taskId = event.dataTransfer.getData('text/plain') || draggedTaskId; if (!taskId) return; let movedTask: Task | undefined; const withoutTask = stages.map(stage => ({ ...stage, tasks: stage.tasks.filter(task => { if (task.id === taskId) movedTask = task; return task.id !== taskId; }) })); if (!movedTask) return; const nextStages = withoutTask.map(stage => { if (stage.id !== targetStageId) return stage; const tasks = [...stage.tasks]; const index = beforeTaskId ? tasks.findIndex(task => task.id === beforeTaskId) : -1; tasks.splice(index < 0 ? tasks.length : index, 0, movedTask!); return { ...stage, tasks }; }); onChange(nextStages); setDraggedTaskId(null); setDropTargetId(null); onNotify('Tarefa movida.'); };

  return <section className="task-section" aria-labelledby="tasks-title">
    <div className="section-heading"><div><p className="eyebrow">Operação</p><h2 id="tasks-title">Mapa de entregas</h2><p>Pesquise, filtre e acompanhe cada responsabilidade.</p></div><div className="filters" role="group" aria-label="Filtros do quadro"><label className="search-field"><Search size={16} /><span className="sr-only">Buscar tarefas</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar tarefas" /></label><select value={stageFilter} onChange={event => setStageFilter(event.target.value)} aria-label="Filtrar por etapa"><option>Todos</option>{stages.map(stage => <option key={stage.id}>{stage.name}</option>)}</select><select value={priority} onChange={event => setPriority(event.target.value)} aria-label="Filtrar por prioridade"><option>Todas</option>{Object.entries(priorityNames).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></div></div>
    {undo && <div className="undo-bar" role="status"><span><Undo2 size={15} /> Tarefa removida: {undo.title}</span><button onClick={restore}>Desfazer</button></div>}
    <div className="stages">{filtered.map(stage => <article className={`stage ${stage.id}${dropTargetId === stage.id ? ' drop-target' : ''}`} key={stage.id} onDragOver={event => { event.preventDefault(); event.dataTransfer.dropEffect = 'move'; setDropTargetId(stage.id); }} onDragLeave={event => { if (!event.currentTarget.contains(event.relatedTarget as Node)) setDropTargetId(null); }} onDrop={event => handleDrop(event, stage.id)}><div className="stage-bar" style={{ background: stage.color }} /><div className="stage-body"><div className="stage-title"><h3>{stage.name}</h3><span className="count">{stage.tasks.length} itens</span></div><p>{stage.description}</p>{stage.tasks.length === 0 && <div className="empty-state compact">Nenhuma tarefa encontrada.</div>}{stage.tasks.map(task => <div className={`task${draggedTaskId === task.id ? ' dragging' : ''}`} key={task.id} draggable onDragStart={event => handleDragStart(event, task.id)} onDragEnd={() => { setDraggedTaskId(null); setDropTargetId(null); }} onDragOver={event => { event.preventDefault(); event.stopPropagation(); setDropTargetId(stage.id); }} onDrop={event => handleDrop(event, stage.id, task.id)}><button className="drag-handle" aria-label={`Arrastar ${task.title}`} tabIndex={-1}><GripVertical size={15} /></button><span className="task-dot" /><div className="task-card"><div className="task-main"><strong>{task.title}</strong><span className={`priority ${task.priority}`}>{priorityNames[task.priority]}</span></div><div className="task-meta">{task.assignee && <span>{task.assignee}</span>}{task.dueDate && <span><Clock3 size={12} /> {formatDate(task.dueDate)}</span>}{task.labels.map(label => <span className="tag" key={label}>{label}</span>)}</div><div className="task-actions"><button onClick={() => openEdit(task, stage.id)}>Editar</button><button onClick={() => remove(stage.id, task)} aria-label={`Excluir ${task.title}`}><Trash2 size={13} /></button>{task.history.length > 0 && <button onClick={() => onNotify(`${task.history.length} alterações registradas nesta tarefa.`)} aria-label={`Ver histórico de ${task.title}`}><History size={13} /></button>}</div></div></div>)}{adding === stage.id ? <div className="quick-add"><input autoFocus placeholder="Nome da tarefa" value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })} onKeyDown={event => event.key === 'Enter' && add(stage.id)} /><button className="primary-button" onClick={() => add(stage.id)}><Check size={15} /> Adicionar</button><button className="icon-button" onClick={() => setAdding(null)} aria-label="Cancelar"><X size={15} /></button></div> : <button className="add-task" onClick={() => { setAdding(stage.id); setDraft(emptyDraft); }}><Plus size={15} /> Adicionar tarefa</button>}</div></article>)}</div>
    {editing && <div className="modal-backdrop" role="presentation" onMouseDown={event => event.target === event.currentTarget && setEditing(null)}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="edit-task-title"><div className="modal-heading"><div><p className="eyebrow">Detalhes</p><h3 id="edit-task-title">Editar tarefa</h3></div><button className="icon-button" onClick={() => setEditing(null)} aria-label="Fechar"><X size={17} /></button></div><div className="form-grid"><label>Título<input autoFocus value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })} /></label><label>Responsável<input value={draft.assignee} onChange={event => setDraft({ ...draft, assignee: event.target.value })} placeholder="Nome" /></label><label>Prazo<input type="date" value={draft.dueDate} onChange={event => setDraft({ ...draft, dueDate: event.target.value })} /></label><label>Prioridade<select value={draft.priority} onChange={event => setDraft({ ...draft, priority: event.target.value as Priority })}>{Object.entries(priorityNames).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></label><label>Etiquetas<input value={draft.labels} onChange={event => setDraft({ ...draft, labels: event.target.value })} placeholder="conteúdo, urgente" /></label></div>{editing.task.history.length > 0 && <details className="history"><summary><History size={15} /> Histórico da tarefa</summary>{editing.task.history.map(item => <p key={item.id}><strong>{item.action}</strong> {item.detail}</p>)}</details>}<div className="form-actions"><button className="primary-button" onClick={save}><Check size={15} /> Salvar alterações</button><button className="secondary-button" onClick={() => setEditing(null)}>Cancelar</button></div></div></div>}
  </section>;
}
